### ISSUE TITLE
there is a bug in msfrpc.py 

### ISSUE THREAD

**Issue by IamRoadRunner** [isaudits/msfrpc_console#1]
use('post', 'aix/hashdump'),  msfrpc.py  line 1334  >>>setattr(self, k, self._info.get(k)) will print  can't set attribute
you can find the attribute 'options' need 'setter'

**Comment by mcjon3z** [comment]
msfrpc.py is a subtree pulled from the pymetasploit project and it appears they have an open PR to correct the same issue, but it is old; the project does not appear to be actively maintained anymore and will likely require me to base the subtree on a fork in order to implement a fix.

https://github.com/allfro/pymetasploit/issues/11

Can you provide details on how to duplicate the error?

**Comment by mcjon3z** [comment]
https://github.com/isaudits/msfrpc_console/commit/e8e3e47cf9b568f16b8d58d49ce8b92318f2cdda

Updated source repo for pymetasploit dependency to https://github.com/Mikaayenson/pymetasploit and merged those commits which included fix for the above referenced.
